version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todda_ai_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - todda_ai_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: todda_ai_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todda_ai_network
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data:

networks:
  todda_ai_network:
    driver: bridge
